### ISSUE TITLE
Provide font as ttf

### ISSUE THREAD

**Issue by Neo-Oli** [kakwa/kakwafont#1]
A *.ttf of this font would be great and allow easier installation on different systems and be used as a web font.

**Comment by RichHammond** [comment]
I'd like this as a ttf as well, due to me being on windows. I'd love to use this as a font in notepad++, as well as other applications.

**Comment by kakwa** [comment]
It's not really possible.

TrueType Font (ttf) is a vector format. kakwafont is a bdf font, which is a raster format.

This request is basically equivalent to requesting a conversion from BMP or JPG to SVG.

It might be possible to hack something together with potrace:
* http://potrace.sourceforge.net/
* https://github.com/koemaeda/potrace-pixelperfect

or use some converters (that don't seem well maintained by the way):
* https://github.com/ali1234/bitmap2ttf
* https://github.com/koron/bdf2ttf

But this will be left as an exercise to the reader as it feels a too hacky process in my opinion.

**Comment by kakwa** [comment]
I've added an `otb` target to generate an opentype font (using fontforge).
